### ISSUE TITLE
Zoomed in extent is unlimited (Restrict zoom to 5 periods width)

### ISSUE THREAD

**Issue by tlsim** [ScottLogic/d3fc-showcase#168]
It's possible to zoom in too far using the mousewheel causing a failed render:
`Invalid value for <path> attribute d="M-Infinity,-466.1657812499783L-Infinity` ... 

Zooming in on the primary or nav chart beyond the error causes the chart's zoom level to 'wrap around' and render using the full nav domain.

**Comment by djmiley** [comment]
Implement maximum zoom on `sc.util.zoomControl`?

**Comment by CBarrett2** [comment]
It's a bit tricky because scale on the zoom behavior refers only to the new scale level for the current event - the best approach imo would be to only zoom in if the viewDomain is still going to show at least the size of one period of data (we can put this on the dataModel), else size the viewDomain to be exactly one period of data

**Comment by djmiley** [comment]
Can throttle zoom, ask Rob what he thinks?

**Comment by djmiley** [comment]
Confirmed

**Comment by djmiley** [comment]
We want to restrict zoom-in to more than 5 of the selected data period, see #273 for implementation on zoom.

**Comment by djmiley** [comment]
Working with Nav brush is much more tricky. Expected behaviour is as follows:

1. Attempting to decrease brush extent to less than minimum results in no movement of brush even when the mouse passes the point where the brush changes its orientation. Increasing back in the previous direction results in expected behaviour. (There is no 'flip' of the brush)

2. When selecting a new domain, we can select as small a domain as possible (which is rendered) until we select over the minimum. After this, we revert to the behaviour in 1.

**Comment by djmiley** [comment]
My work on this
https://github.com/djmiley/d3fc-showcase/tree/bug/zoominextent

**Comment by djmiley** [comment]
Question- should the nav bar update continuously in `on('brush')`, or should it be restricted to only update in `on('brushend')`? Restricting to 'on('brushend') would make solving this far easier,

**Comment by jleft** [comment]
Duplicated by #499 (reopen if you disagree :))
