### ISSUE TITLE
The time period selector should be disabled when loading data

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc-showcase#505]
Try rapidly clicking between '1 Hr' and 'Daily' ... you get a 429 HTTP response after a while.

**Comment by rjmcneill** [comment]
Throttled in PR #476

**Comment by jleft** [comment]
The rate limit for the Coinbase API is 1 request / second.

We decided to debounce the API requests (in #476), which avoids the limit being reached, rather than disabling the selectors. We thought this would provide a better experience for the user, so they can still change period whilst the data is loading.

Please reopen if this isn't a suitable solution :)
