### ISSUE TITLE
API request failures should be reported to the user

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc-showcase#506]
see #505 - we should display some form of user-friendly message - and an apology!

**Comment by tlsim** [comment]
Latest develop has this covered with #478 ?

**Comment by jdhodges431** [comment]
Can we close this one?

**Comment by jleft** [comment]
I believe this is fixed in the `develop` branch. For example:

![error-toasts](https://cloud.githubusercontent.com/assets/2017615/12119148/e3fcbe86-b3c1-11e5-97bb-83d0a023cb30.PNG)

To see these messages, go to: http://scottlogic.github.io/d3fc-showcase/develop/# select `BTC-USD` product and click the `1 Min` button rapidly (more than once per second) and the error messages should appear.

I think the messages are fairly user-friendly, we could add an apology though! Any thoughts @ColinEberhardt? Is this the sort of thing you had in mind?

**Comment by ColinEberhardt** [comment]
I think that will do just fine for now - thanks :-)
