### ISSUE TITLE
Question regarding the navigator brush extent and scroll zooming

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/d3fc-showcase#539]
If you use the scroll wheel to zoom in on a selected element and your navigator brush extent is not extended to its full width, then you zoom in on the selected element.

If you use the scroll wheel to zoom in on a selected element and your navigator brush extent IS extended to its full width, then you dont zoom in on the selected element, instead its the furthest right.

This behavior is not consistent and is somewhat confusing to a user. Is it intentional?
For example:
[bandicam 2016-01-13 10-46-12-485.zip](https://github.com/ScottLogic/d3fc-showcase/files/88723/bandicam.2016-01-13.10-46-12-485.zip)

**Comment by jleft** [comment]
Good spot :) thanks for the video - makes it really easy to understand the issue.

It is inconsistent and it's not immediately obvious why, but this is intentional and the expected behaviour.

---

The idea is that if the navigator brush extent is touching the right-most edge of the chart, then we're tracking the latest price. If it's not, then we're not tracking the latest price.

As the latest price is, arguably, the most important piece of information on the chart - if the user is viewing it (i.e. the navigator brush extent is touching the right-most edge of the chart), then we make sure it stays in the viewport when the user zooms; if the latest price isn't being tracked, then we revert to the default behaviour, where we zoom in around the cursor.

**Comment by jleft** [comment]
Please feel free to reopen if I've missed anything! :)
